// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSQRfqh_d4Nsse1oDghmzDTuAgxvxvrK0',
    appId: '1:170204797988:web:b70480e09ffe554756ccb1',
    messagingSenderId: '170204797988',
    projectId: 'musium-project',
    authDomain: 'musium-project.firebaseapp.com',
    storageBucket: 'musium-project.appspot.com',
    measurementId: 'G-2H5Q90TB8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_lJbpzO8b_IIxhSFkQPCFQk6of0BShs',
    appId: '1:170204797988:android:e00291b6eb6acbd456ccb1',
    messagingSenderId: '170204797988',
    projectId: 'musium-project',
    storageBucket: 'musium-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq92Yj3e2n2aEsP9a-ZaDrwofqtQ0Qnf0',
    appId: '1:170204797988:ios:40ae86528dc35b1f56ccb1',
    messagingSenderId: '170204797988',
    projectId: 'musium-project',
    storageBucket: 'musium-project.appspot.com',
    androidClientId: '170204797988-scjk3q5ftkkfm1dgm0ncv889gv1efn3v.apps.googleusercontent.com',
    iosClientId: '170204797988-ibb0qjtrk060hvrelvbddl0s8ss702a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.golobe',
  );
}
